cc_library(
    name = "solver",
    srcs = [
        "NozzleSolver.cpp",
    ],
    hdrs = [
        "NozzleSolver.h",
    ],
    deps = [
        "//src/MOC_2D/common:common",
        "//src/MOC_2D/config:config",
        "@mp-units//:mp-units",
    ],
    visibility = ["//visibility:public"],
)
