cc_library(
    name = "config",
    hdrs = [
        "Configuration.h",
        "Problem.h",
    ],
    srcs = [
        "Configuration.cpp",
        "Problem.cpp",
    ],
    deps = ["@mp-units//:mp-units"],
    visibility = ["//visibility:public"],
)
