cc_library(
    name = "common",
    hdrs = [
        "Math.h",
        "GridPoint.h"
    ],
    srcs = [
        "Math.cpp",
        "GridPoint.cpp"
    ],
    deps = ["@mp-units//:mp-units"],
    visibility = ["//visibility:public"],
)
