cc_library(
    name = "common",
    hdrs = [
        "Math.h",
        "Grid.h",
        "Result.h",
    ],
    srcs = [
        "Math.cpp",
        "Grid.cpp",
        "Result.cpp",
    ],
    deps = ["@mp-units//:mp-units"],
    visibility = ["//visibility:public"],
)
