cc_test(
    name = "moc_legacy_test",
    srcs = ["moc_legacy_test.cpp"],
    deps = [
        "//src/MOC_Grid_BDE:MOC_Grid_BDE",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
    copts = ["-std=c++23"],
    size = "medium",
)
